server:
  port: 7000
spring:
  cloud:
    gateway:
      routes:
      - id: serv-vuelos
        uri: lb://vuelos
        predicates:
          - Path=/svuelos/**
        filters:
          - RewritePath=/svuelos/*, /

      - id: serv-hoteles
        uri: lb://hoteles
        predicates:
          - Path=/shoteles/**
        filters:
          - RewritePath=/shoteles/*, /

      - id: serv-reservas
        uri: lb://reservas
        predicates:
          - Path=/sreservas/**
        filters:
          - RewritePath=/sreservas/*, /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
